CREATE TABLE IF NOT EXISTS android_metadata(locale TEXT DEFAULT 'es_ES');
CREATE TABLE IF NOT EXISTS zones(name TEXT PRIMARY KEY NOT NULL);
CREATE TABLE IF NOT EXISTS monsters(_id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,zone TEXT NOT NULL REFERENCES zones(name),count INTEGER NOT NULL DEFAULT '0');