CREATE TABLE android_metadata(locale TEXT DEFAULT 'es_ES');
CREATE TABLE zones(name TEXT PRIMARY KEY NOT NULL);
CREATE TABLE monstruos(_id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,zone TEXT NOT NULL REFERENCES zones(name),count INTEGER NOT NULL DEFAULT '0');