INSERT INTO android_metadata VALUES ('es_ES');
INSERT INTO zones VALUES ('Besaid');
INSERT INTO zones VALUES ('Kilika');
INSERT INTO zones VALUES ('Camino de Miihen');
INSERT INTO zones VALUES ('Senda de las Rocas Hongo');
INSERT INTO zones VALUES ('Camino de Djose');
INSERT INTO zones VALUES ('Llanura de los Rayos');
INSERT INTO zones VALUES ('Macalania');
INSERT INTO zones VALUES ('Bikanel');
INSERT INTO zones VALUES ('Llanura de la Calma');
INSERT INTO zones VALUES ('Cueva del barranco');
INSERT INTO zones VALUES ('Monte Gagazet');
INSERT INTO zones VALUES ('Interior de Sinh');
INSERT INTO zones VALUES ('Ruinas Omega');
INSERT INTO monsters(name,zone,count) VALUES ('Dingo','Besaid',0);
INSERT INTO monsters(name,zone,count) VALUES ('Condor','Besaid',0);
INSERT INTO monsters(name,zone,count) VALUES ('Flan de agua','Besaid',0);
INSERT INTO monsters(name,zone,count) VALUES ('Dinonix','Kilika',0);
INSERT INTO monsters(name,zone,count) VALUES ('Abeja asesina','Kilika',0);
INSERT INTO monsters(name,zone,count) VALUES ('Ente amarillo','Kilika',0);
INSERT INTO monsters(name,zone,count) VALUES ('Barsam','Kilika',0);
INSERT INTO monsters(name,zone,count) VALUES ('Fang de Miihen','Camino de Miihen',0);
INSERT INTO monsters(name,zone,count) VALUES ('Hiperia','Camino de Miihen',0);
INSERT INTO monsters(name,zone,count) VALUES ('Ojo flotante','Camino de Miihen',0);
INSERT INTO monsters(name,zone,count) VALUES ('Ente blanco','Camino de Miihen',0);
INSERT INTO monsters(name,zone,count) VALUES ('Petro','Camino de Miihen',0);
INSERT INTO monsters(name,zone,count) VALUES ('Vihur','Camino de Miihen',0);
INSERT INTO monsters(name,zone,count) VALUES ('Bom','Camino de Miihen',0);
INSERT INTO monsters(name,zone,count) VALUES ('Bicornio','Camino de Miihen',0);
INSERT INTO monsters(name,zone,count) VALUES ('raptor','Senda de las Rocas Hongo',0);
INSERT INTO monsters(name,zone,count) VALUES ('Gandarva','Senda de las Rocas Hongo',0);
INSERT INTO monsters(name,zone,count) VALUES ('Flan eléctrico','Senda de las Rocas Hongo',0);
INSERT INTO monsters(name,zone,count) VALUES ('Ente rojo','Senda de las Rocas Hongo',0);
INSERT INTO monsters(name,zone,count) VALUES ('Ramashu','Senda de las Rocas Hongo',0);
INSERT INTO monsters(name,zone,count) VALUES ('Fungo','Senda de las Rocas Hongo',0);
INSERT INTO monsters(name,zone,count) VALUES ('Garuda','Senda de las Rocas Hongo',0);
INSERT INTO monsters(name,zone,count) VALUES ('Garmú','Camino de Djose',0);
INSERT INTO monsters(name,zone,count) VALUES ('Quebrantahuesos','Camino de Djose',0);
INSERT INTO monsters(name,zone,count) VALUES ('Mosquito','Camino de Djose',0);
INSERT INTO monsters(name,zone,count) VALUES ('Flan de nieve','Camino de Djose',0);
INSERT INTO monsters(name,zone,count) VALUES ('Lasca','Camino de Djose',0);
INSERT INTO monsters(name,zone,count) VALUES ('Basilisco','Camino de Djose',0);
INSERT INTO monsters(name,zone,count) VALUES ('Ochú','Camino de Djose',0);
INSERT INTO monsters(name,zone,count) VALUES ('Gecko','Llanura de los Rayos',0);
INSERT INTO monsters(name,zone,count) VALUES ('Airos','Llanura de los Rayos',0);
INSERT INTO monsters(name,zone,count) VALUES ('Buel','Llanura de los Rayos',0);
INSERT INTO monsters(name,zone,count) VALUES ('Ente dorado','Llanura de los Rayos',0);
INSERT INTO monsters(name,zone,count) VALUES ('Kusarik','Llanura de los Rayos',0);
INSERT INTO monsters(name,zone,count) VALUES ('Máscara','Llanura de los Rayos',0);
INSERT INTO monsters(name,zone,count) VALUES ('Férreo','Llanura de los Rayos',0);
INSERT INTO monsters(name,zone,count) VALUES ('Cactilio X','Llanura de los Rayos',0);
INSERT INTO monsters(name,zone,count) VALUES ('Lobo de nieves','Macalania',0);
INSERT INTO monsters(name,zone,count) VALUES ('Iguion','Macalania',0);
INSERT INTO monsters(name,zone,count) VALUES ('Avispa','Macalania',0);
INSERT INTO monsters(name,zone,count) VALUES ('Ojo diabólico','Macalania',0);
INSERT INTO monsters(name,zone,count) VALUES ('Flan de hielo','Macalania',0);
INSERT INTO monsters(name,zone,count) VALUES ('Ente azul','Macalania',0);
INSERT INTO monsters(name,zone,count) VALUES ('Mulfú','Macalania',0);
INSERT INTO monsters(name,zone,count) VALUES ('Mafú','Macalania',0);
INSERT INTO monsters(name,zone,count) VALUES ('Kuspo','Macalania',0);
INSERT INTO monsters(name,zone,count) VALUES ('Quimera','Macalania',0);
INSERT INTO monsters(name,zone,count) VALUES ('Lobo del desierto','Bikanel',0);
INSERT INTO monsters(name,zone,count) VALUES ('Halcón','Bikanel',0);
INSERT INTO monsters(name,zone,count) VALUES ('Mushufushu','Bikanel',0);
INSERT INTO monsters(name,zone,count) VALUES ('Zu','Bikanel',0);
INSERT INTO monsters(name,zone,count) VALUES ('Gusano de arena','Bikanel',0);
INSERT INTO monsters(name,zone,count) VALUES ('Cactilio','Bikanel',0);
INSERT INTO monsters(name,zone,count) VALUES ('Dole','Llanura de la Calma',0);
INSERT INTO monsters(name,zone,count) VALUES ('Véspida','Llanura de la Calma',0);
INSERT INTO monsters(name,zone,count) VALUES ('Flan de llamas','Llanura de la Calma',0);
INSERT INTO monsters(name,zone,count) VALUES ('Shred','Llanura de la Calma',0);
INSERT INTO monsters(name,zone,count) VALUES ('Dracmón','Llanura de la Calma',0);
INSERT INTO monsters(name,zone,count) VALUES ('Ogro','Llanura de la Calma',0);
INSERT INTO monsters(name,zone,count) VALUES ('Bengal','Llanura de la Calma',0);
INSERT INTO monsters(name,zone,count) VALUES ('Quimera negra','Llanura de la Calma',0);
INSERT INTO monsters(name,zone,count) VALUES ('Molbol','Llanura de la Calma',0);
INSERT INTO monsters(name,zone,count) VALUES ('Yovi','Cueva del barranco',0);
INSERT INTO monsters(name,zone,count) VALUES ('Galkimasera','Cueva del barranco',0);
INSERT INTO monsters(name,zone,count) VALUES ('Ente oscuro','Cueva del barranco',0);
INSERT INTO monsters(name,zone,count) VALUES ('Sigurd','Cueva del barranco',0);
INSERT INTO monsters(name,zone,count) VALUES ('Septa','Cueva del barranco',0);
INSERT INTO monsters(name,zone,count) VALUES ('Vraha','Cueva del barranco',0);
INSERT INTO monsters(name,zone,count) VALUES ('Everge','Cueva del barranco',0);
INSERT INTO monsters(name,zone,count) VALUES ('Fantasma','Cueva del barranco',0);
INSERT INTO monsters(name,zone,count) VALUES ('Tomberi','Cueva del barranco',0);
INSERT INTO monsters(name,zone,count) VALUES ('Mal Bernardo','Monte Gagazet',0);
INSERT INTO monsters(name,zone,count) VALUES ('Arimán','Monte Gagazet',0);
INSERT INTO monsters(name,zone,count) VALUES ('Flan oscuro','Monte Gagazet',0);
INSERT INTO monsters(name,zone,count) VALUES ('Granada','Monte Gagazet',0);
INSERT INTO monsters(name,zone,count) VALUES ('Grat','Monte Gagazet',0);
INSERT INTO monsters(name,zone,count) VALUES ('Grendel','Monte Gagazet',0);
INSERT INTO monsters(name,zone,count) VALUES ('Asur','Monte Gagazet',0);
INSERT INTO monsters(name,zone,count) VALUES ('Mandrágora','Monte Gagazet',0);
INSERT INTO monsters(name,zone,count) VALUES ('Bégimo','Monte Gagazet',0);
INSERT INTO monsters(name,zone,count) VALUES ('Pez luchador','Monte Gagazet',0);
INSERT INTO monsters(name,zone,count) VALUES ('Aqueoros','Monte Gagazet',0);
INSERT INTO monsters(name,zone,count) VALUES ('Tritón','Monte Gagazet',0);
INSERT INTO monsters(name,zone,count) VALUES ('Amanita','Interior de Sinh',0);
INSERT INTO monsters(name,zone,count) VALUES ('Caronte','Interior de Sinh',0);
INSERT INTO monsters(name,zone,count) VALUES ('Gigante','Interior de Sinh',0);
INSERT INTO monsters(name,zone,count) VALUES ('Monolito diabólico','Interior de Sinh',0);
INSERT INTO monsters(name,zone,count) VALUES ('Gran molbol','Interior de Sinh',0);
INSERT INTO monsters(name,zone,count) VALUES ('Barbatos','Interior de Sinh',0);
INSERT INTO monsters(name,zone,count) VALUES ('Adamantaimai','Interior de Sinh',0);
INSERT INTO monsters(name,zone,count) VALUES ('Rey Bégimo','Interior de Sinh',0);
INSERT INTO monsters(name,zone,count) VALUES ('Gigante 2','Interior de Sinh',0);
INSERT INTO monsters(name,zone,count) VALUES ('Saurio','Ruinas Omega',0);
INSERT INTO monsters(name,zone,count) VALUES ('Desfiot','Ruinas Omega',0);
INSERT INTO monsters(name,zone,count) VALUES ('Ente negro','Ruinas Omega',0);
INSERT INTO monsters(name,zone,count) VALUES ('Haruma','Ruinas Omega',0);
INSERT INTO monsters(name,zone,count) VALUES ('Ignitio','Ruinas Omega',0);
INSERT INTO monsters(name,zone,count) VALUES ('Espíritu','Ruinas Omega',0);
INSERT INTO monsters(name,zone,count) VALUES ('Meich','Ruinas Omega',0);
INSERT INTO monsters(name,zone,count) VALUES ('Gran bengal','Ruinas Omega',0);
INSERT INTO monsters(name,zone,count) VALUES ('Mestro tomberi','Ruinas Omega',0);
INSERT INTO monsters(name,zone,count) VALUES ('Varn','Ruinas Omega',0);