INSERT INTO android_metadata VALUES ('es_ES');
INSERT INTO zones VALUES ('Besaid');
INSERT INTO zones VALUES ('Kilika');
INSERT INTO zones VALUES ('Camino de Miihen');
INSERT INTO zones VALUES ('Senda de las Rocas Hongo');
INSERT INTO zones VALUES ('Camino de Djose');
INSERT INTO zones VALUES ('Llanura de los Rayos');
INSERT INTO zones VALUES ('Macalania');
INSERT INTO zones VALUES ('Bikanel');
INSERT INTO zones VALUES ('Llanura de la Calma');
INSERT INTO zones VALUES ('Cueva del barranco');
INSERT INTO zones VALUES ('Monte  Gagazet');
INSERT INTO zones VALUES ('Interior de Sinh');
INSERT INTO zones VALUES ('Ruinas Omega');
INSERT INTO monstruos VALUES ('Dingo','Besaid',0);
INSERT INTO monstruos VALUES ('Condor','Besaid',0);
INSERT INTO monstruos VALUES ('Flan de agua','Besaid',0);
INSERT INTO monstruos VALUES ('Dinonix','Kilika',0);
INSERT INTO monstruos VALUES ('Abeja asesina','Kilika',0);
INSERT INTO monstruos VALUES ('Ente amarillo','Kilika',0);
INSERT INTO monstruos VALUES ('Barsam','Kilika',0);
INSERT INTO monstruos VALUES ('Fang de Miihen','Camino de Miihen',0);
INSERT INTO monstruos VALUES ('Hiperia','Camino de Miihen',0);
INSERT INTO monstruos VALUES ('Ojo flotante','Camino de Miihen',0);
INSERT INTO monstruos VALUES ('Ente blanco','Camino de Miihen',0);
INSERT INTO monstruos VALUES ('Petro','Camino de Miihen',0);
INSERT INTO monstruos VALUES ('Vihur','Camino de Miihen',0);
INSERT INTO monstruos VALUES ('Bom','Camino de Miihen',0);
INSERT INTO monstruos VALUES ('Bicornio','Camino de Miihen',0);
INSERT INTO monstruos VALUES ('raptor','Sendas de las Rocas Hongo',0);
INSERT INTO monstruos VALUES ('Gandarva','Sendas de las Rocas Hongo',0);
INSERT INTO monstruos VALUES ('Flan eléctrico','Sendas de las Rocas Hongo',0);
INSERT INTO monstruos VALUES ('Ente rojo','Sendas de las Rocas Hongo',0);
INSERT INTO monstruos VALUES ('Ramashu','Sendas de las Rocas Hongo',0);
INSERT INTO monstruos VALUES ('Fungo','Sendas de las Rocas Hongo',0);
INSERT INTO monstruos VALUES ('Garuda','Sendas de las Rocas Hongo',0);
INSERT INTO monstruos VALUES ('Garmú','Camino de Djose',0);
INSERT INTO monstruos VALUES ('Quebrantahuesos','Camino de Djose',0);
INSERT INTO monstruos VALUES ('Mosquito','Camino de Djose',0);
INSERT INTO monstruos VALUES ('Flan de nieve','Camino de Djose',0);
INSERT INTO monstruos VALUES ('Lasca','Camino de Djose',0);
INSERT INTO monstruos VALUES ('Basilisco','Camino de Djose',0);
INSERT INTO monstruos VALUES ('Ochú','Camino de Djose',0);
INSERT INTO monstruos VALUES ('Gecko','Llanura de los Rayos',0);
INSERT INTO monstruos VALUES ('Airos','Llanura de los Rayos',0);
INSERT INTO monstruos VALUES ('Buel','Llanura de los Rayos',0);
INSERT INTO monstruos VALUES ('Ente dorado','Llanura de los Rayos',0);
INSERT INTO monstruos VALUES ('Kusarik','Llanura de los Rayos',0);
INSERT INTO monstruos VALUES ('Máscara','Llanura de los Rayos',0);
INSERT INTO monstruos VALUES ('Férreo','Llanura de los Rayos',0);
INSERT INTO monstruos VALUES ('Cactilio X','Llanura de los Rayos',0);
INSERT INTO monstruos VALUES ('Lobo de nieves','Macalania',0);
INSERT INTO monstruos VALUES ('Iguion','Macalania',0);
INSERT INTO monstruos VALUES ('Avispa','Macalania',0);
INSERT INTO monstruos VALUES ('Ojo diabólico','Macalania',0);
INSERT INTO monstruos VALUES ('Flan de hielo','Macalania',0);
INSERT INTO monstruos VALUES ('Ente azul','Macalania',0);
INSERT INTO monstruos VALUES ('Mulfú','Macalania',0);
INSERT INTO monstruos VALUES ('Mafú','Macalania',0);
INSERT INTO monstruos VALUES ('Kuspo','Macalania',0);
INSERT INTO monstruos VALUES ('Quimera','Macalania',0);
INSERT INTO monstruos VALUES ('Lobo del desierto','Bikanel',0);
INSERT INTO monstruos VALUES ('Halcón','Bikanel',0);
INSERT INTO monstruos VALUES ('Mushufushu','Bikanel',0);
INSERT INTO monstruos VALUES ('Zu','Bikanel',0);
INSERT INTO monstruos VALUES ('Gusano de arena','Bikanel',0);
INSERT INTO monstruos VALUES ('Cactilio','Bikanel',0);
INSERT INTO monstruos VALUES ('Dole','Llanura de la Calma',0);
INSERT INTO monstruos VALUES ('Véspida','Llanura de la Calma',0);
INSERT INTO monstruos VALUES ('Flan de llamas','Llanura de la Calma',0);
INSERT INTO monstruos VALUES ('Shred','Llanura de la Calma',0);
INSERT INTO monstruos VALUES ('Dracmón','Llanura de la Calma',0);
INSERT INTO monstruos VALUES ('Ogro','Llanura de la Calma',0);
INSERT INTO monstruos VALUES ('Bengal','Llanura de la Calma',0);
INSERT INTO monstruos VALUES ('Quimera negra','Llanura de la Calma',0);
INSERT INTO monstruos VALUES ('Molbol','Llanura de la Calma',0);
INSERT INTO monstruos VALUES ('Yovi','Cueva del barranco',0);
INSERT INTO monstruos VALUES ('Galkimasera','Cueva del barranco',0);
INSERT INTO monstruos VALUES ('Ente oscuro','Cueva del barranco',0);
INSERT INTO monstruos VALUES ('Sigurd','Cueva del barranco',0);
INSERT INTO monstruos VALUES ('Septa','Cueva del barranco',0);
INSERT INTO monstruos VALUES ('Vraha','Cueva del barranco',0);
INSERT INTO monstruos VALUES ('Everge','Cueva del barranco',0);
INSERT INTO monstruos VALUES ('Fantasma','Cueva del barranco',0);
INSERT INTO monstruos VALUES ('Tomberi','Cueva del barranco',0);
INSERT INTO monstruos VALUES ('Mal Bernardo','Monte Gagazet',0);
INSERT INTO monstruos VALUES ('Arimán','Monte Gagazet',0);
INSERT INTO monstruos VALUES ('Flan oscuro','Monte Gagazet',0);
INSERT INTO monstruos VALUES ('Granada','Monte Gagazet',0);
INSERT INTO monstruos VALUES ('Grat','Monte Gagazet',0);
INSERT INTO monstruos VALUES ('Grendel','Monte Gagazet',0);
INSERT INTO monstruos VALUES ('Asur','Monte Gagazet',0);
INSERT INTO monstruos VALUES ('Mandrágora','Monte Gagazet',0);
INSERT INTO monstruos VALUES ('Bégimo','Monte Gagazet',0);
INSERT INTO monstruos VALUES ('Pez luchador','Monte Gagazet',0);
INSERT INTO monstruos VALUES ('Aqueoros','Monte Gagazet',0);
INSERT INTO monstruos VALUES ('Tritón','Monte Gagazet',0);
INSERT INTO monstruos VALUES ('Amanita','Interior de Sinh',0);
INSERT INTO monstruos VALUES ('Caronte','Interior de Sinh',0);
INSERT INTO monstruos VALUES ('Gigante','Interior de Sinh',0);
INSERT INTO monstruos VALUES ('Monolito diabólico','Interior de Sinh',0);
INSERT INTO monstruos VALUES ('Gran molbol','Interior de Sinh',0);
INSERT INTO monstruos VALUES ('Barbatos','Interior de Sinh',0);
INSERT INTO monstruos VALUES ('Adamantaimai','Interior de Sinh',0);
INSERT INTO monstruos VALUES ('Rey Bégimo','Interior de Sinh',0);
INSERT INTO monstruos VALUES ('Gigante 2','Interior de Sinh',0);
INSERT INTO monstruos VALUES ('Saurio','Ruinas Omega',0);
INSERT INTO monstruos VALUES ('Desfiot','Ruinas Omega',0);
INSERT INTO monstruos VALUES ('Ente negro','Ruinas Omega',0);
INSERT INTO monstruos VALUES ('Haruma','Ruinas Omega',0);
INSERT INTO monstruos VALUES ('Ignitio','Ruinas Omega',0);
INSERT INTO monstruos VALUES ('Espíritu','Ruinas Omega',0);
INSERT INTO monstruos VALUES ('Meich','Ruinas Omega',0);
INSERT INTO monstruos VALUES ('Gran bengal','Ruinas Omega',0);
INSERT INTO monstruos VALUES ('Mestro tomberi','Ruinas Omega',0);
INSERT INTO monstruos VALUES ('Varn','Ruinas Omega',0);