INSERT INTO android_metadata VALUES ('es_ES');
INSERT INTO zones VALUES ('Besaid');
INSERT INTO zones VALUES ('Kilika');
INSERT INTO zones VALUES ('Camino de Miihen');
INSERT INTO zones VALUES ('Senda de las Rocas Hongo');
INSERT INTO zones VALUES ('Camino de Djose');
INSERT INTO zones VALUES ('Llanura de los Rayos');
INSERT INTO zones VALUES ('Macalania');
INSERT INTO zones VALUES ('Bikanel');
INSERT INTO zones VALUES ('Llanura de la Calma');
INSERT INTO zones VALUES ('Cueva del barranco');
INSERT INTO zones VALUES ('Monte  Gagazet');
INSERT INTO zones VALUES ('Interior de Sinh');
INSERT INTO zones VALUES ('Ruinas Omega');
INSERT INTO monsters VALUES ('Dingo','Besaid',0);
INSERT INTO monsters VALUES ('Condor','Besaid',0);
INSERT INTO monsters VALUES ('Flan de agua','Besaid',0);
INSERT INTO monsters VALUES ('Dinonix','Kilika',0);
INSERT INTO monsters VALUES ('Abeja asesina','Kilika',0);
INSERT INTO monsters VALUES ('Ente amarillo','Kilika',0);
INSERT INTO monsters VALUES ('Barsam','Kilika',0);
INSERT INTO monsters VALUES ('Fang de Miihen','Camino de Miihen',0);
INSERT INTO monsters VALUES ('Hiperia','Camino de Miihen',0);
INSERT INTO monsters VALUES ('Ojo flotante','Camino de Miihen',0);
INSERT INTO monsters VALUES ('Ente blanco','Camino de Miihen',0);
INSERT INTO monsters VALUES ('Petro','Camino de Miihen',0);
INSERT INTO monsters VALUES ('Vihur','Camino de Miihen',0);
INSERT INTO monsters VALUES ('Bom','Camino de Miihen',0);
INSERT INTO monsters VALUES ('Bicornio','Camino de Miihen',0);
INSERT INTO monsters VALUES ('raptor','Sendas de las Rocas Hongo',0);
INSERT INTO monsters VALUES ('Gandarva','Sendas de las Rocas Hongo',0);
INSERT INTO monsters VALUES ('Flan eléctrico','Sendas de las Rocas Hongo',0);
INSERT INTO monsters VALUES ('Ente rojo','Sendas de las Rocas Hongo',0);
INSERT INTO monsters VALUES ('Ramashu','Sendas de las Rocas Hongo',0);
INSERT INTO monsters VALUES ('Fungo','Sendas de las Rocas Hongo',0);
INSERT INTO monsters VALUES ('Garuda','Sendas de las Rocas Hongo',0);
INSERT INTO monsters VALUES ('Garmú','Camino de Djose',0);
INSERT INTO monsters VALUES ('Quebrantahuesos','Camino de Djose',0);
INSERT INTO monsters VALUES ('Mosquito','Camino de Djose',0);
INSERT INTO monsters VALUES ('Flan de nieve','Camino de Djose',0);
INSERT INTO monsters VALUES ('Lasca','Camino de Djose',0);
INSERT INTO monsters VALUES ('Basilisco','Camino de Djose',0);
INSERT INTO monsters VALUES ('Ochú','Camino de Djose',0);
INSERT INTO monsters VALUES ('Gecko','Llanura de los Rayos',0);
INSERT INTO monsters VALUES ('Airos','Llanura de los Rayos',0);
INSERT INTO monsters VALUES ('Buel','Llanura de los Rayos',0);
INSERT INTO monsters VALUES ('Ente dorado','Llanura de los Rayos',0);
INSERT INTO monsters VALUES ('Kusarik','Llanura de los Rayos',0);
INSERT INTO monsters VALUES ('Máscara','Llanura de los Rayos',0);
INSERT INTO monsters VALUES ('Férreo','Llanura de los Rayos',0);
INSERT INTO monsters VALUES ('Cactilio X','Llanura de los Rayos',0);
INSERT INTO monsters VALUES ('Lobo de nieves','Macalania',0);
INSERT INTO monsters VALUES ('Iguion','Macalania',0);
INSERT INTO monsters VALUES ('Avispa','Macalania',0);
INSERT INTO monsters VALUES ('Ojo diabólico','Macalania',0);
INSERT INTO monsters VALUES ('Flan de hielo','Macalania',0);
INSERT INTO monsters VALUES ('Ente azul','Macalania',0);
INSERT INTO monsters VALUES ('Mulfú','Macalania',0);
INSERT INTO monsters VALUES ('Mafú','Macalania',0);
INSERT INTO monsters VALUES ('Kuspo','Macalania',0);
INSERT INTO monsters VALUES ('Quimera','Macalania',0);
INSERT INTO monsters VALUES ('Lobo del desierto','Bikanel',0);
INSERT INTO monsters VALUES ('Halcón','Bikanel',0);
INSERT INTO monsters VALUES ('Mushufushu','Bikanel',0);
INSERT INTO monsters VALUES ('Zu','Bikanel',0);
INSERT INTO monsters VALUES ('Gusano de arena','Bikanel',0);
INSERT INTO monsters VALUES ('Cactilio','Bikanel',0);
INSERT INTO monsters VALUES ('Dole','Llanura de la Calma',0);
INSERT INTO monsters VALUES ('Véspida','Llanura de la Calma',0);
INSERT INTO monsters VALUES ('Flan de llamas','Llanura de la Calma',0);
INSERT INTO monsters VALUES ('Shred','Llanura de la Calma',0);
INSERT INTO monsters VALUES ('Dracmón','Llanura de la Calma',0);
INSERT INTO monsters VALUES ('Ogro','Llanura de la Calma',0);
INSERT INTO monsters VALUES ('Bengal','Llanura de la Calma',0);
INSERT INTO monsters VALUES ('Quimera negra','Llanura de la Calma',0);
INSERT INTO monsters VALUES ('Molbol','Llanura de la Calma',0);
INSERT INTO monsters VALUES ('Yovi','Cueva del barranco',0);
INSERT INTO monsters VALUES ('Galkimasera','Cueva del barranco',0);
INSERT INTO monsters VALUES ('Ente oscuro','Cueva del barranco',0);
INSERT INTO monsters VALUES ('Sigurd','Cueva del barranco',0);
INSERT INTO monsters VALUES ('Septa','Cueva del barranco',0);
INSERT INTO monsters VALUES ('Vraha','Cueva del barranco',0);
INSERT INTO monsters VALUES ('Everge','Cueva del barranco',0);
INSERT INTO monsters VALUES ('Fantasma','Cueva del barranco',0);
INSERT INTO monsters VALUES ('Tomberi','Cueva del barranco',0);
INSERT INTO monsters VALUES ('Mal Bernardo','Monte Gagazet',0);
INSERT INTO monsters VALUES ('Arimán','Monte Gagazet',0);
INSERT INTO monsters VALUES ('Flan oscuro','Monte Gagazet',0);
INSERT INTO monsters VALUES ('Granada','Monte Gagazet',0);
INSERT INTO monsters VALUES ('Grat','Monte Gagazet',0);
INSERT INTO monsters VALUES ('Grendel','Monte Gagazet',0);
INSERT INTO monsters VALUES ('Asur','Monte Gagazet',0);
INSERT INTO monsters VALUES ('Mandrágora','Monte Gagazet',0);
INSERT INTO monsters VALUES ('Bégimo','Monte Gagazet',0);
INSERT INTO monsters VALUES ('Pez luchador','Monte Gagazet',0);
INSERT INTO monsters VALUES ('Aqueoros','Monte Gagazet',0);
INSERT INTO monsters VALUES ('Tritón','Monte Gagazet',0);
INSERT INTO monsters VALUES ('Amanita','Interior de Sinh',0);
INSERT INTO monsters VALUES ('Caronte','Interior de Sinh',0);
INSERT INTO monsters VALUES ('Gigante','Interior de Sinh',0);
INSERT INTO monsters VALUES ('Monolito diabólico','Interior de Sinh',0);
INSERT INTO monsters VALUES ('Gran molbol','Interior de Sinh',0);
INSERT INTO monsters VALUES ('Barbatos','Interior de Sinh',0);
INSERT INTO monsters VALUES ('Adamantaimai','Interior de Sinh',0);
INSERT INTO monsters VALUES ('Rey Bégimo','Interior de Sinh',0);
INSERT INTO monsters VALUES ('Gigante 2','Interior de Sinh',0);
INSERT INTO monsters VALUES ('Saurio','Ruinas Omega',0);
INSERT INTO monsters VALUES ('Desfiot','Ruinas Omega',0);
INSERT INTO monsters VALUES ('Ente negro','Ruinas Omega',0);
INSERT INTO monsters VALUES ('Haruma','Ruinas Omega',0);
INSERT INTO monsters VALUES ('Ignitio','Ruinas Omega',0);
INSERT INTO monsters VALUES ('Espíritu','Ruinas Omega',0);
INSERT INTO monsters VALUES ('Meich','Ruinas Omega',0);
INSERT INTO monsters VALUES ('Gran bengal','Ruinas Omega',0);
INSERT INTO monsters VALUES ('Mestro tomberi','Ruinas Omega',0);
INSERT INTO monsters VALUES ('Varn','Ruinas Omega',0);